1.Back/src/HairSalon.UI.Web/Controllers/CompanyController.cs
using System;
using System.Threading.Tasks;
using HairSalon.Application.Interfaces;
using HairSalon.Application.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetDevPack.Identity.Authorization;

namespace HairSalon.UI.Web.Controllers
{
    [Authorize]
    public class CompanyController : BaseController
    {
        private readonly ICompanyAppService _companyAppService;

        public CompanyController(ICompanyAppService companyAppService)
        {
            _companyAppService = companyAppService;
        }
        [HttpGet("company-management/list-all")]
        public async Task<IActionResult> Index()
        {
            return View(await _companyAppService.GetAll());
        }

        [HttpGet("company-management/company-details/{id:long}")]
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null) return NotFound();

            var customerViewModel = await _companyAppService.GetById(id.Value);

            if (customerViewModel == null) return NotFound();

            return View(customerViewModel);
        }

        //[CustomAuthorize("Companies", "Write")]
        [HttpGet("company-management/create")]
        public IActionResult Create()
        {
            return View();
        }

        //[CustomAuthorize("Customers", "Write")]
        [HttpPost("company-management/create")]
        public async Task<IActionResult> Create(CompanyViewModel companyViewModel)
        {
            if (!ModelState.IsValid) return View(companyViewModel);

            if (ResponseHasErrors(await _companyAppService.Create(companyViewModel)))
                return View(companyViewModel);

            ViewBag.Success = "Company Created!";

            return View(companyViewModel);
        }

    }
}

1.Back/src/HairSalon.UI.Web/ViewComponents/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.UI.Web.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("Default");
        }
    }
}

1.Back/src/HairSalon.UI.Web/Views/Company/Create.cshtml
@model HairSalon.Application.ViewModels.CompanyViewModel

@{
    ViewData["Title"] = "Create new Company";
}

<h2></h2>

<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-6">
                <form asp-action="Create">
                    <div class="card">
                        <div class="card-header"><strong>@ViewData["Title"]</strong> <small></small></div>
                        <div class="card-body">
                            <vc:summary />
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="Name"></label>
                                        <input asp-for="Name" class="form-control" placeholder="Enter company name" />
                                        <span asp-validation-for="Name" class="invalid-feedback"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="Email"></label>
                                        <input asp-for="Email" class="form-control" placeholder="Enter company email" />
                                        <span asp-validation-for="Email" class="invalid-feedback"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="TaxNumber"></label>
                                        <input asp-for="TaxNumber" class="form-control" placeholder="Enter tax number" />
                                        <span asp-validation-for="TaxNumber" class="invalid-feedback"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <input type="submit" value="Create" class="btn btn-sm btn-success" />
                            <a asp-action="Index" class="btn btn-sm btn-info">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

1.Back/src/HairSalon.UI.Web/Views/Company/Delete.cshtml
@model HairSalon.Application.ViewModels.CompanyViewModel

@{
    ViewData["Title"] = "Delete Company";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Delete">
    <vc:summary />

    <h3>Are you sure you want to delete the @Model.Name?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TaxNumber)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TaxNumber)
            </dd>
        </dl>


        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-info">Back to List</a>
        </div>
    </div>
</form>

1.Back/src/HairSalon.UI.Web/Views/Company/Details.cshtml
@model HairSalon.Application.ViewModels.CompanyViewModel

@{
    ViewData["Title"] = "Company Details";
}

<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-6">
                <form asp-action="Edit">
                    <input type="hidden" asp-for="Id" />
                    <div class="card">
                        <div class="card-header"><strong>@ViewData["Title"]</strong> <small></small></div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong>@Html.DisplayNameFor(model => model.Name)</strong>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    @Html.DisplayFor(model => model.Name)
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong>@Html.DisplayNameFor(model => model.Email)</strong>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    @Html.DisplayFor(model => model.Email)
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong>@Html.DisplayNameFor(model => model.TaxNumber)</strong>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    @Html.DisplayFor(model => model.TaxNumber)
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-warning">Edit</a>
                            <a asp-action="Index" class="btn btn-sm btn-info">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

1.Back/src/HairSalon.UI.Web/Views/Company/Edit.cshtml
@model HairSalon.Application.ViewModels.CompanyViewModel

@{
    ViewData["Title"] = "Edit Company";
}

<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-6">
                <form asp-action="Edit">
                    <input type="hidden" asp-for="Id" />
                    <div class="card">
                        <div class="card-header"><strong>@ViewData["Title"]</strong> <small></small></div>
                        <div class="card-body">
                            <vc:summary />
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="Name"></label>
                                        <input asp-for="Name" class="form-control" placeholder="Enter company name" />
                                        <span asp-validation-for="Name" class="invalid-feedback"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="Email"></label>
                                        <input asp-for="Email" class="form-control" placeholder="Enter company email" />
                                        <span asp-validation-for="Email" class="invalid-feedback"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label asp-for="TaxNumber"></label>
                                        <input asp-for="TaxNumber" class="form-control" placeholder="Enter company tax number" />
                                        <span asp-validation-for="TaxNumber" class="invalid-feedback"></span>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <input type="submit" value="Save" class="btn btn-sm btn-success" />
                            <a asp-action="Index" class="btn btn-sm btn-info">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

1.Back/src/HairSalon.UI.Web/Views/Company/Index.cshtml
@model IEnumerable<HairSalon.Application.ViewModels.CompanyViewModel>

@{
    ViewData["Title"] = "Company Management";
}

<style>
    .modal-lg {
        max-width: 80%;
    }
</style>

<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong>@ViewData["Title"]</strong>
                        <div class="pull-right">
                            <a asp-action="Create" class="btn btn-primary btn-sm">
                                Create Company
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-responsive-md">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TaxNumber)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TaxNumber)
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.Id" title="Edit" class="btn btn-sm btn-warning">
                                                Edit
                                                @*<span class="fas fa-edit"></span>*@
                                            </a>

                                            <a asp-action="Details" asp-route-id="@item.Id" title="Details" class="btn btn-sm btn-primary">
                                                View
                                                @*<span class="fas fa-search"></span>*@
                                            </a>

                                            <a asp-action="Delete" asp-route-id="@item.Id" title="Delete" class="btn btn-sm btn-danger">
                                                Delete
                                                @*<span class="fas fa-trash-alt"></span>*@
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
    </script>
}